name: Build KOALA Optimizer C# Edition

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Framework
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: nuget/setup-nuget@v2
      with:
        nuget-version: 'latest'

    - name: Restore NuGet packages
      run: |
        nuget restore KOALAOptimizer.Testing/packages.config -PackagesDirectory packages
      shell: cmd

    - name: Build the C# WPF application
      run: |
        msbuild KOALAOptimizer.Testing/KOALAOptimizer.Testing.csproj /p:Configuration=Release /p:Platform="AnyCPU" /p:OutputPath=bin/Release/ /verbosity:minimal
      shell: cmd

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: KOALAOptimizer-Release
        path: KOALAOptimizer.Testing/bin/Release/
        if-no-files-found: error

    - name: List output files (debug)
      run: |
        echo "Contents of Release folder:"
        dir KOALAOptimizer.Testing\bin\Release\ /s
      shell: cmd
