name: Build KOALA Optimizer V3

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Release
    
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
      continue-on-error: true
    
    - name: Publish
      run: dotnet publish -c Release -o publish
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: KOALA-Optimizer-V3-Build
        path: publish/
        retention-days: 30
