name: Build and Release KOALA Optimizer C# Edition

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Restore packages
      run: dotnet restore "KOALAOptimizer.Testing\KOALAOptimizer.Testing.csproj"

    - name: Build project
      run: dotnet build "KOALAOptimizer.Testing\KOALAOptimizer.Testing.csproj" -c Release

    - name: Publish as single file
      run: |
        dotnet publish "KOALAOptimizer.Testing\KOALAOptimizer.Testing.csproj" -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o publish

    - name: List published files
      run: |
        echo "Files in publish directory:"
        dir publish
      shell: cmd

    - name: Create artifact directory
      run: |
        mkdir artifact
        copy publish\*.exe artifact\
        echo KOALA Gaming Optimizer V3 > artifact\README.txt
        echo Created by KOALAaufPILLEN >> artifact\README.txt
        echo Build Date: 2025-08-20 18:44:36 >> artifact\README.txt
        dir artifact
      shell: cmd

    - name: Upload executable artifact
      uses: actions/upload-artifact@v3
      with:
        name: KOALA-Optimizer-V3
        path: artifact/*

    - name: Alternative upload (if v3 fails)
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: KOALA-Optimizer-V3-alt
        path: publish/KOALAOptimizer.Testing.exe
