name: Build KOALA Optimizer V3

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
    
    - name: Build Single EXE
      run: |
        cd KOALAOptimizer.Testing
        dotnet publish -c Release -r win-x64 --self-contained -p:PublishSingleFile=true -o ../output
        cd ..
        dir output
    
    - name: Prepare Release Package
      run: |
        mkdir release
        copy output\KOALAOptimizer.Testing.exe release\KOALA-Optimizer.exe
        echo KOALA Gaming Optimizer V3 > release\README.txt
        echo By KOALAaufPILLEN >> release\README.txt
        dir release
      shell: cmd
    
    - name: Upload Artifact V4
      uses: actions/upload-artifact@v4
      with:
        name: KOALA-Optimizer-EXE
        path: release/
        retention-days: 90
    
    - name: Create ZIP and Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        powershell Compress-Archive -Path release\* -DestinationPath KOALA-V3.zip
        
        gh release create v3.0.${{ github.run_number }} KOALA-V3.zip `
          --title "KOALA V3 Build ${{ github.run_number }}" `
          --notes "KOALA Gaming Optimizer V3 - Download KOALA-V3.zip" `
          --latest
      env:
        GH_TOKEN: ${{ github.token }}
      shell: powershell
      continue-on-error: true
