name: Build KOALA Optimizer C# Edition

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: nuget/setup-nuget@v2

    - name: Create packages directory
      run: |
        if not exist "packages" mkdir packages
      shell: cmd

    - name: Restore NuGet packages for the project
      run: |
        nuget restore KOALAOptimizer.Testing\packages.config -PackagesDirectory packages
      shell: cmd

    - name: Build the project
      run: |
        msbuild "KOALAOptimizer.Testing\KOALAOptimizer.Testing.csproj" ^
        /p:Configuration=Release ^
        /p:Platform=AnyCPU ^
        /p:UseSharedCompilation=false ^
        /p:BuildInParallel=false ^
        /p:RestorePackages=false ^
        /verbosity:normal
      shell: cmd

    - name: Verify build output
      run: |
        if exist "KOALAOptimizer.Testing\bin\Release\KOALAOptimizer.Testing.exe" (
          echo Build successful - executable found
          dir "KOALAOptimizer.Testing\bin\Release\"
        ) else (
          echo Build failed - executable not found
          exit 1
        )
      shell: cmd

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: KOALAOptimizer-Release
        path: KOALAOptimizer.Testing/bin/Release/
        if-no-files-found: error
