name: Final Working Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
    
    - name: COMPLETE BUILD WITH ALL FIXES
      run: |
        cd KOALAOptimizer.Testing
        
        echo "=== CLEANING EVERYTHING ==="
        rmdir /s /q bin 2>nul
        rmdir /s /q obj 2>nul
        del *.csproj 2>nul
        
        echo.
        echo "=== CREATING COMPLETE PROJECT FILE ==="
        (
          echo ^<Project Sdk="Microsoft.NET.Sdk"^>
          echo   ^<PropertyGroup^>
          echo     ^<OutputType^>WinExe^</OutputType^>
          echo     ^<TargetFramework^>net8.0-windows^</TargetFramework^>
          echo     ^<UseWPF^>true^</UseWPF^>
          echo     ^<AssemblyName^>KOALAOptimizer^</AssemblyName^>
          echo     ^<RootNamespace^>KOALAOptimizer^</RootNamespace^>
          echo     ^<ApplicationIcon^>koala.ico^</ApplicationIcon^>
          echo     ^<GenerateAssemblyInfo^>false^</GenerateAssemblyInfo^>
          echo   ^</PropertyGroup^>
          echo   ^<ItemGroup^>
          echo     ^<PackageReference Include="System.Management" Version="8.0.0" /^>
          echo     ^<PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" /^>
          echo   ^</ItemGroup^>
          echo ^</Project^>
        ) > KOALAOptimizer.Testing.csproj
        
        echo.
        echo "=== CREATING AssemblyInfo.cs ==="
        if not exist Properties mkdir Properties
        (
          echo using System.Reflection;
          echo using System.Runtime.InteropServices;
          echo [assembly: AssemblyTitle^("KOALA Optimizer"^)]
          echo [assembly: AssemblyCompany^("KOALAaufPILLEN"^)]
          echo [assembly: AssemblyProduct^("KOALA V3"^)]
          echo [assembly: AssemblyVersion^("3.0.0.0"^)]
          echo [assembly: AssemblyFileVersion^("3.0.0.0"^)]
          echo [assembly: AssemblyConfiguration^(""^)]
          echo [assembly: ComVisible^(false^)]
        ) > Properties\AssemblyInfo.cs
        
        echo.
        echo "=== RESTORING PACKAGES ==="
        dotnet restore
        
        echo.
        echo "=== BUILDING ==="
        dotnet build -c Release --no-restore
        
        echo.
        echo "=== PUBLISHING ==="
        dotnet publish -c Release -r win-x64 --self-contained -p:PublishSingleFile=true --no-build -o ..\output
        
        cd ..
        
        echo.
        echo "=== BUILD SUCCESSFUL! ==="
        dir output
      shell: cmd
    
    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: KOALA-V3-FINAL-${{ github.run_number }}
        path: output/
    
    - name: Create ZIP and Release
      run: |
        cd output
        ren *.exe KOALA-Optimizer-V3.exe
        cd ..
        
        powershell Compress-Archive -Path output\KOALA-Optimizer-V3.exe -DestinationPath KOALA-V3-WORKING.zip
        
        echo Files created:
        dir *.zip
        
        gh release delete v3.0-final -y 2>nul
        gh release create v3.0-final KOALA-V3-WORKING.zip --title "🐨 KOALA V3.0 FINAL WORKING" --notes "Finally working! By KOALAaufPILLEN" --latest
      env:
        GH_TOKEN: ${{ github.token }}
      shell: cmd
      continue-on-error: true
