name: Build KOALA V3 PS1 Style

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
    
    - name: Create PS1-Style KOALA Project
      run: |
        cd KOALAOptimizer.Testing
        
        Write-Host "=== CLEANING OLD FILES ==="
        Remove-Item -Path bin, obj -Recurse -Force -ErrorAction SilentlyContinue
        Remove-Item -Path *.cs, *.xaml, *.csproj -Force -ErrorAction SilentlyContinue
        
        Write-Host "=== CREATING PS1-STYLE UI FILES ==="
        
        # Create directories
        New-Item -ItemType Directory -Path Properties -Force | Out-Null
        
        # Create the PS1-style MainWindow.xaml with base64 encoding to avoid issues
        $xamlContent = @'
<Window x:Class="KOALAOptimizer.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="KOALA Gaming Optimizer v3.0" Height="900" Width="1400"
        Background="#0a0a0a" WindowStartupLocation="CenterScreen">
    <Window.Resources>
        <Style TargetType="CheckBox">
            <Setter Property="Foreground" Value="White"/>
            <Setter Property="Margin" Value="5,2"/>
        </Style>
        <Style TargetType="GroupBox">
            <Setter Property="Foreground" Value="#00ff00"/>
            <Setter Property="BorderBrush" Value="#00ff00"/>
            <Setter Property="Margin" Value="5"/>
        </Style>
    </Window.Resources>
    
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto"/>
            <RowDefinition Height="Auto"/>
            <RowDefinition Height="*"/>
            <RowDefinition Height="Auto"/>
            <RowDefinition Height="200"/>
        </Grid.RowDefinitions>

        <Border Grid.Row="0" Background="#00ff00" Padding="10">
            <StackPanel>
                <TextBlock Text="KOALA Gaming Optimizer v3.0" FontSize="20" FontWeight="Bold" Foreground="Black"/>
                <TextBlock Text="Advanced Windows gaming optimizations with comprehensive FPS-boosting features!" 
                           FontSize="11" Foreground="#333"/>
            </StackPanel>
        </Border>

        <WrapPanel Grid.Row="1" Background="#1a1a1a" Margin="5">
            <CheckBox Name="AdvancedNetworking" Content="Advanced Networking" IsChecked="True" FontWeight="Bold"/>
            <CheckBox Name="DisableTCP" Content="Disable TCP ACK Delay" IsChecked="True"/>
            <CheckBox Name="TurboNagle" Content="Turbo NAGLE/ACK" IsChecked="True"/>
            <CheckBox Name="DisableNetThrottling" Content="Disable Network Throttling" IsChecked="True"/>
        </WrapPanel>

        <ScrollViewer Grid.Row="2" VerticalScrollBarVisibility="Auto">
            <StackPanel Margin="10">
                <TextBlock Text="Windows Gaming Optimizations" Foreground="#00ff00" FontWeight="Bold" FontSize="14" Margin="0,10,0,5"/>
                <WrapPanel>
                    <CheckBox Name="SystemResponsiveness" Content="System Responsiveness" IsChecked="True"/>
                    <CheckBox Name="GamesPriority" Content="Games Task High Priority" IsChecked="True"/>
                    <CheckBox Name="DisableGameDVR" Content="Disable Game DVR" IsChecked="True"/>
                    <CheckBox Name="DisableFullscreenOpt" Content="Disable Fullscreen Optimizations" IsChecked="True"/>
                    <CheckBox Name="EnableGPUScheduling" Content="Enable GPU Hardware Scheduling" IsChecked="True"/>
                    <CheckBox Name="HighPrecisionTimer" Content="High Precision Timer" IsChecked="True"/>
                </WrapPanel>

                <TextBlock Text="Enhanced Gaming Optimizations" Foreground="#00ff00" FontWeight="Bold" FontSize="14" Margin="0,10,0,5"/>
                <WrapPanel>
                    <CheckBox Name="EnhancedCPU" Content="Enhanced CPU Affinity" IsChecked="True"/>
                    <CheckBox Name="AdvancedMemory" Content="Advanced Memory Optimization" IsChecked="True"/>
                    <CheckBox Name="GPUDriverOpt" Content="GPU Driver Optimizations" IsChecked="True"/>
                    <CheckBox Name="NetworkLatency" Content="Network Latency Improvements" IsChecked="True"/>
                </WrapPanel>

                <TextBlock Text="Advanced FPS-Boosting" Foreground="#00ff00" FontWeight="Bold" FontSize="14" Margin="0,10,0,5"/>
                <WrapPanel>
                    <CheckBox Name="CPUCoreParking" Content="CPU Core Parking Disable" IsChecked="True"/>
                    <CheckBox Name="CPUCStates" Content="CPU C-States Disable" IsChecked="True"/>
                    <CheckBox Name="InterruptMode" Content="Interrupt Moderation" IsChecked="True"/>
                    <CheckBox Name="MSIMode" Content="MSI/MSI-X Gaming Priority" IsChecked="True"/>
                </WrapPanel>

                <TextBlock Text="Background Services" Foreground="#00ff00" FontWeight="Bold" FontSize="14" Margin="0,10,0,5"/>
                <WrapPanel>
                    <CheckBox Name="DisableXboxServices" Content="Disable Xbox Services" IsChecked="True"/>
                    <CheckBox Name="DisableTelemetry" Content="Disable Telemetry" IsChecked="True"/>
                    <CheckBox Name="DisableWindowsSearch" Content="Disable Windows Search"/>
                </WrapPanel>
            </StackPanel>
        </ScrollViewer>

        <Border Grid.Row="3" Background="#1a1a1a" Padding="10" Margin="5">
            <Grid>
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="Auto"/>
                    <ColumnDefinition Width="300"/>
                    <ColumnDefinition Width="*"/>
                </Grid.ColumnDefinitions>
                <TextBlock Grid.Column="0" Text="Game Profile:" Foreground="White" VerticalAlignment="Center" Margin="0,0,10,0"/>
                <ComboBox Grid.Column="1" Name="GameProfileCombo" Margin="0,0,10,0">
                    <ComboBoxItem>Counter-Strike 2</ComboBoxItem>
                    <ComboBoxItem>Valorant</ComboBoxItem>
                    <ComboBoxItem>Fortnite</ComboBoxItem>
                    <ComboBoxItem>Apex Legends</ComboBoxItem>
                </ComboBox>
                <StackPanel Grid.Column="2" Orientation="Horizontal">
                    <Button Name="AutoDetect" Content="Auto Detect" Background="#6a0dad" Foreground="White" Padding="10,5" Margin="5,0"/>
                    <Button Name="RecommendedButton" Content="Recommended" Background="#00ff00" Foreground="Black" Padding="10,5" Margin="5,0" Click="Recommended_Click"/>
                    <Button Name="RevertAllButton" Content="Revert All" Background="#ff3333" Foreground="White" Padding="10,5" Margin="5,0" Click="RevertAll_Click"/>
                </StackPanel>
            </Grid>
        </Border>

        <Grid Grid.Row="4">
            <GroupBox Header="Activity Log" Margin="5">
                <ScrollViewer>
                    <TextBox Name="LogBox" Background="#0a0a0a" Foreground="#00ff00" IsReadOnly="True" FontFamily="Consolas"/>
                </ScrollViewer>
            </GroupBox>
        </Grid>
    </Grid>
</Window>
'@
        
        $xamlContent | Out-File -FilePath MainWindow.xaml -Encoding UTF8
        
        # Create MainWindow.xaml.cs
        @'
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Management;
using System.Runtime.InteropServices;
using System.Windows;
using System.Windows.Controls;
using Microsoft.Win32;
using System.Threading.Tasks;
using System.Linq;

namespace KOALAOptimizer
{
    public partial class MainWindow : Window
    {
        [DllImport("winmm.dll")]
        static extern uint timeBeginPeriod(uint period);
        
        [DllImport("winmm.dll")]
        static extern uint timeEndPeriod(uint period);

        public MainWindow()
        {
            InitializeComponent();
            LoadSystemInfo();
            timeBeginPeriod(1);
            LogMessage("KOALA Gaming Optimizer v3.0 Ready");
            LogMessage("Advanced optimizations loaded");
        }

        private void LoadSystemInfo()
        {
            try
            {
                string cpuInfo = "Unknown CPU";
                using (var searcher = new ManagementObjectSearcher("SELECT * FROM Win32_Processor"))
                {
                    foreach (var obj in searcher.Get())
                    {
                        cpuInfo = obj["Name"].ToString();
                        break;
                    }
                }
                LogMessage($"System: {cpuInfo}");
            }
            catch { }
        }

        private void LogMessage(string msg)
        {
            string timestamp = DateTime.Now.ToString("HH:mm:ss");
            LogBox.AppendText($"[{timestamp}] {msg}\n");
            LogBox.ScrollToEnd();
        }

        private void Recommended_Click(object sender, RoutedEventArgs e)
        {
            LogMessage("Applying recommended optimizations...");
            Task.Run(async () =>
            {
                await ApplyOptimizations();
                await Dispatcher.InvokeAsync(() =>
                {
                    LogMessage("Optimizations complete!");
                    MessageBox.Show("All recommended optimizations applied!", "KOALA V3", MessageBoxButton.OK, MessageBoxImage.Information);
                });
            });
        }

        private async Task ApplyOptimizations()
        {
            // Network optimizations
            if (DisableTCP.IsChecked == true)
            {
                await Dispatcher.InvokeAsync(() => LogMessage("Disabling TCP ACK delay..."));
                try
                {
                    Registry.SetValue(@"HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters", "TcpNoDelay", 1, RegistryValueKind.DWord);
                    Registry.SetValue(@"HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters", "TcpDelAckTicks", 0, RegistryValueKind.DWord);
                }
                catch { }
            }

            // Gaming optimizations
            if (DisableGameDVR.IsChecked == true)
            {
                await Dispatcher.InvokeAsync(() => LogMessage("Disabling Game DVR..."));
                try
                {
                    Registry.SetValue(@"HKEY_CURRENT_USER\System\GameConfigStore", "GameDVR_Enabled", 0, RegistryValueKind.DWord);
                    Registry.SetValue(@"HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\GameDVR", "AppCaptureEnabled", 0, RegistryValueKind.DWord);
                }
                catch { }
            }

            // GPU scheduling
            if (EnableGPUScheduling.IsChecked == true)
            {
                await Dispatcher.InvokeAsync(() => LogMessage("Enabling GPU hardware scheduling..."));
                try
                {
                    Registry.SetValue(@"HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "HwSchMode", 2, RegistryValueKind.DWord);
                }
                catch { }
            }

            // System responsiveness
            if (SystemResponsiveness.IsChecked == true)
            {
                await Dispatcher.InvokeAsync(() => LogMessage("Optimizing system responsiveness..."));
                try
                {
                    Registry.SetValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile", "SystemResponsiveness", 0, RegistryValueKind.DWord);
                    Registry.SetValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games", "GPU Priority", 8, RegistryValueKind.DWord);
                    Registry.SetValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games", "Priority", 6, RegistryValueKind.DWord);
                }
                catch { }
            }

            await Task.Delay(500);
        }

        private void RevertAll_Click(object sender, RoutedEventArgs e)
        {
            LogMessage("Reverting all optimizations...");
            // Revert logic here
            LogMessage("All optimizations reverted");
        }

        protected override void OnClosed(EventArgs e)
        {
            base.OnClosed(e);
            timeEndPeriod(1);
        }
    }
}
'@ | Out-File -FilePath MainWindow.xaml.cs -Encoding UTF8

        # Create App.xaml
        @'
<Application x:Class="KOALAOptimizer.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             StartupUri="MainWindow.xaml">
    <Application.Resources>
    </Application.Resources>
</Application>
'@ | Out-File -FilePath App.xaml -Encoding UTF8

        # Create App.xaml.cs
        @'
using System.Windows;

namespace KOALAOptimizer
{
    public partial class App : Application
    {
    }
}
'@ | Out-File -FilePath App.xaml.cs -Encoding UTF8

        # Create project file
        @'
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <UseWPF>true</UseWPF>
    <AssemblyName>KOALAOptimizer</AssemblyName>
    <RootNamespace>KOALAOptimizer</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Management" Version="8.0.0" />
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
  </ItemGroup>
</Project>
'@ | Out-File -FilePath KOALAOptimizer.Testing.csproj -Encoding UTF8

        # Create AssemblyInfo
        @'
using System.Reflection;
[assembly: AssemblyTitle("KOALA Gaming Optimizer V3")]
[assembly: AssemblyCompany("KOALAaufPILLEN")]
[assembly: AssemblyProduct("KOALA Gaming Optimizer")]
[assembly: AssemblyVersion("3.0.0.0")]
'@ | Out-File -FilePath Properties\AssemblyInfo.cs -Encoding UTF8

        Write-Host "=== PS1-STYLE FILES CREATED ==="
        Get-ChildItem
      shell: pwsh
    
    - name: Build and Publish
      run: |
        cd KOALAOptimizer.Testing
        
        Write-Host "=== RESTORE ==="
        dotnet restore
        
        Write-Host "=== BUILD ==="
        dotnet build -c Release
        
        Write-Host "=== PUBLISH ==="
        dotnet publish -c Release -o ../output
        
        cd ..
        
        Write-Host "=== BUILD COMPLETE! ==="
        Get-ChildItem output
      shell: pwsh
    
    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: KOALA-V3-PS1-STYLE
        path: output/
