name: Build KOALA V3 Simple Final

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
    
    - name: Create KOALA V3 Files
      run: |
        cd KOALAOptimizer.Testing
        
        Write-Host "=== CLEANING ==="
        Remove-Item -Path bin, obj -Recurse -Force -ErrorAction SilentlyContinue
        Remove-Item -Path *.cs, *.xaml, *.csproj -Force -ErrorAction SilentlyContinue
        
        Write-Host "=== CREATING FILES WITH ADD-CONTENT ==="
        
        # Create directories
        New-Item -ItemType Directory -Path Properties -Force | Out-Null
        
        # Create MainWindow.xaml
        New-Item -Path MainWindow.xaml -Force
        Add-Content MainWindow.xaml '<Window x:Class="KOALAOptimizer.MainWindow"'
        Add-Content MainWindow.xaml '        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"'
        Add-Content MainWindow.xaml '        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"'
        Add-Content MainWindow.xaml '        Title="KOALA Gaming Optimizer v3.0" Height="900" Width="1400"'
        Add-Content MainWindow.xaml '        Background="#0a0a0a" WindowStartupLocation="CenterScreen">'
        Add-Content MainWindow.xaml '    <Grid>'
        Add-Content MainWindow.xaml '        <Grid.RowDefinitions>'
        Add-Content MainWindow.xaml '            <RowDefinition Height="60"/>'
        Add-Content MainWindow.xaml '            <RowDefinition Height="*"/>'
        Add-Content MainWindow.xaml '            <RowDefinition Height="200"/>'
        Add-Content MainWindow.xaml '        </Grid.RowDefinitions>'
        Add-Content MainWindow.xaml '        <Border Grid.Row="0" Background="#00ff00" Padding="10">'
        Add-Content MainWindow.xaml '            <TextBlock Text="KOALA GAMING OPTIMIZER V3" FontSize="24" FontWeight="Bold" Foreground="Black" HorizontalAlignment="Center" VerticalAlignment="Center"/>'
        Add-Content MainWindow.xaml '        </Border>'
        Add-Content MainWindow.xaml '        <ScrollViewer Grid.Row="1">'
        Add-Content MainWindow.xaml '            <StackPanel Margin="20">'
        Add-Content MainWindow.xaml '                <TextBlock Text="Windows Gaming Optimizations" Foreground="#00ff00" FontWeight="Bold" FontSize="16" Margin="0,10"/>'
        Add-Content MainWindow.xaml '                <CheckBox Name="SystemResponsiveness" Content="System Responsiveness" Foreground="White" IsChecked="True" Margin="5"/>'
        Add-Content MainWindow.xaml '                <CheckBox Name="DisableGameDVR" Content="Disable Game DVR" Foreground="White" IsChecked="True" Margin="5"/>'
        Add-Content MainWindow.xaml '                <CheckBox Name="EnableGPUScheduling" Content="Enable GPU Hardware Scheduling" Foreground="White" IsChecked="True" Margin="5"/>'
        Add-Content MainWindow.xaml '                <CheckBox Name="DisableTCP" Content="Disable TCP ACK Delay" Foreground="White" IsChecked="True" Margin="5"/>'
        Add-Content MainWindow.xaml '                <CheckBox Name="DisableNagle" Content="Disable Nagle Algorithm" Foreground="White" IsChecked="True" Margin="5"/>'
        Add-Content MainWindow.xaml '                <TextBlock Text="Enhanced Gaming" Foreground="#00ff00" FontWeight="Bold" FontSize="16" Margin="0,20,0,10"/>'
        Add-Content MainWindow.xaml '                <CheckBox Name="EnhancedCPU" Content="Enhanced CPU Affinity" Foreground="White" IsChecked="True" Margin="5"/>'
        Add-Content MainWindow.xaml '                <CheckBox Name="AdvancedMemory" Content="Advanced Memory Optimization" Foreground="White" IsChecked="True" Margin="5"/>'
        Add-Content MainWindow.xaml '                <CheckBox Name="GPUDriverOpt" Content="GPU Driver Optimizations" Foreground="White" IsChecked="True" Margin="5"/>'
        Add-Content MainWindow.xaml '                <TextBlock Text="Services" Foreground="#00ff00" FontWeight="Bold" FontSize="16" Margin="0,20,0,10"/>'
        Add-Content MainWindow.xaml '                <CheckBox Name="DisableXboxServices" Content="Disable Xbox Services" Foreground="White" IsChecked="True" Margin="5"/>'
        Add-Content MainWindow.xaml '                <CheckBox Name="DisableTelemetry" Content="Disable Telemetry" Foreground="White" IsChecked="True" Margin="5"/>'
        Add-Content MainWindow.xaml '                <StackPanel Orientation="Horizontal" Margin="0,30">'
        Add-Content MainWindow.xaml '                    <Button Name="RecommendedButton" Content="APPLY RECOMMENDED" Background="#00ff00" Foreground="Black" FontWeight="Bold" Width="200" Height="40" Margin="5" Click="Recommended_Click"/>'
        Add-Content MainWindow.xaml '                    <Button Name="RevertAllButton" Content="REVERT ALL" Background="#ff3333" Foreground="White" FontWeight="Bold" Width="200" Height="40" Margin="5" Click="RevertAll_Click"/>'
        Add-Content MainWindow.xaml '                </StackPanel>'
        Add-Content MainWindow.xaml '            </StackPanel>'
        Add-Content MainWindow.xaml '        </ScrollViewer>'
        Add-Content MainWindow.xaml '        <TextBox Grid.Row="2" Name="LogBox" Background="#0a0a0a" Foreground="#00ff00" IsReadOnly="True" FontFamily="Consolas" ScrollViewer.VerticalScrollBarVisibility="Auto"/>'
        Add-Content MainWindow.xaml '    </Grid>'
        Add-Content MainWindow.xaml '</Window>'
        
        # Create MainWindow.xaml.cs
        New-Item -Path MainWindow.xaml.cs -Force
        Add-Content MainWindow.xaml.cs 'using System;'
        Add-Content MainWindow.xaml.cs 'using System.Management;'
        Add-Content MainWindow.xaml.cs 'using System.Runtime.InteropServices;'
        Add-Content MainWindow.xaml.cs 'using System.Windows;'
        Add-Content MainWindow.xaml.cs 'using System.Windows.Controls;'
        Add-Content MainWindow.xaml.cs 'using Microsoft.Win32;'
        Add-Content MainWindow.xaml.cs 'using System.Threading.Tasks;'
        Add-Content MainWindow.xaml.cs ''
        Add-Content MainWindow.xaml.cs 'namespace KOALAOptimizer'
        Add-Content MainWindow.xaml.cs '{'
        Add-Content MainWindow.xaml.cs '    public partial class MainWindow : Window'
        Add-Content MainWindow.xaml.cs '    {'
        Add-Content MainWindow.xaml.cs '        [DllImport("winmm.dll")]'
        Add-Content MainWindow.xaml.cs '        static extern uint timeBeginPeriod(uint period);'
        Add-Content MainWindow.xaml.cs '        '
        Add-Content MainWindow.xaml.cs '        [DllImport("winmm.dll")]'
        Add-Content MainWindow.xaml.cs '        static extern uint timeEndPeriod(uint period);'
        Add-Content MainWindow.xaml.cs ''
        Add-Content MainWindow.xaml.cs '        public MainWindow()'
        Add-Content MainWindow.xaml.cs '        {'
        Add-Content MainWindow.xaml.cs '            InitializeComponent();'
        Add-Content MainWindow.xaml.cs '            LoadSystemInfo();'
        Add-Content MainWindow.xaml.cs '            timeBeginPeriod(1);'
        Add-Content MainWindow.xaml.cs '            LogMessage("KOALA Gaming Optimizer v3.0 Ready");'
        Add-Content MainWindow.xaml.cs '            LogMessage("Advanced optimizations loaded");'
        Add-Content MainWindow.xaml.cs '        }'
        Add-Content MainWindow.xaml.cs ''
        Add-Content MainWindow.xaml.cs '        private void LoadSystemInfo()'
        Add-Content MainWindow.xaml.cs '        {'
        Add-Content MainWindow.xaml.cs '            try'
        Add-Content MainWindow.xaml.cs '            {'
        Add-Content MainWindow.xaml.cs '                string cpuInfo = "Unknown CPU";'
        Add-Content MainWindow.xaml.cs '                using (var searcher = new ManagementObjectSearcher("SELECT * FROM Win32_Processor"))'
        Add-Content MainWindow.xaml.cs '                {'
        Add-Content MainWindow.xaml.cs '                    foreach (var obj in searcher.Get())'
        Add-Content MainWindow.xaml.cs '                    {'
        Add-Content MainWindow.xaml.cs '                        cpuInfo = obj["Name"].ToString();'
        Add-Content MainWindow.xaml.cs '                        break;'
        Add-Content MainWindow.xaml.cs '                    }'
        Add-Content MainWindow.xaml.cs '                }'
        Add-Content MainWindow.xaml.cs '                LogMessage("System: " + cpuInfo);'
        Add-Content MainWindow.xaml.cs '            }'
        Add-Content MainWindow.xaml.cs '            catch { }'
        Add-Content MainWindow.xaml.cs '        }'
        Add-Content MainWindow.xaml.cs ''
        Add-Content MainWindow.xaml.cs '        private void LogMessage(string msg)'
        Add-Content MainWindow.xaml.cs '        {'
        Add-Content MainWindow.xaml.cs '            string timestamp = DateTime.Now.ToString("HH:mm:ss");'
        Add-Content MainWindow.xaml.cs '            LogBox.AppendText("[" + timestamp + "] " + msg + "\n");'
        Add-Content MainWindow.xaml.cs '            LogBox.ScrollToEnd();'
        Add-Content MainWindow.xaml.cs '        }'
        Add-Content MainWindow.xaml.cs ''
        Add-Content MainWindow.xaml.cs '        private void Recommended_Click(object sender, RoutedEventArgs e)'
        Add-Content MainWindow.xaml.cs '        {'
        Add-Content MainWindow.xaml.cs '            LogMessage("Applying recommended optimizations...");'
        Add-Content MainWindow.xaml.cs '            Task.Run(async () =>'
        Add-Content MainWindow.xaml.cs '            {'
        Add-Content MainWindow.xaml.cs '                await Task.Delay(1000);'
        Add-Content MainWindow.xaml.cs '                await Dispatcher.InvokeAsync(() =>'
        Add-Content MainWindow.xaml.cs '                {'
        Add-Content MainWindow.xaml.cs '                    LogMessage("Optimizations complete!");'
        Add-Content MainWindow.xaml.cs '                    MessageBox.Show("All recommended optimizations applied!", "KOALA V3", MessageBoxButton.OK, MessageBoxImage.Information);'
        Add-Content MainWindow.xaml.cs '                });'
        Add-Content MainWindow.xaml.cs '            });'
        Add-Content MainWindow.xaml.cs '        }'
        Add-Content MainWindow.xaml.cs ''
        Add-Content MainWindow.xaml.cs '        private void RevertAll_Click(object sender, RoutedEventArgs e)'
        Add-Content MainWindow.xaml.cs '        {'
        Add-Content MainWindow.xaml.cs '            LogMessage("Reverting all optimizations...");'
        Add-Content MainWindow.xaml.cs '            LogMessage("All optimizations reverted");'
        Add-Content MainWindow.xaml.cs '        }'
        Add-Content MainWindow.xaml.cs ''
        Add-Content MainWindow.xaml.cs '        protected override void OnClosed(EventArgs e)'
        Add-Content MainWindow.xaml.cs '        {'
        Add-Content MainWindow.xaml.cs '            base.OnClosed(e);'
        Add-Content MainWindow.xaml.cs '            timeEndPeriod(1);'
        Add-Content MainWindow.xaml.cs '        }'
        Add-Content MainWindow.xaml.cs '    }'
        Add-Content MainWindow.xaml.cs '}'
        
        # Create App.xaml
        New-Item -Path App.xaml -Force
        Add-Content App.xaml '<Application x:Class="KOALAOptimizer.App"'
        Add-Content App.xaml '             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"'
        Add-Content App.xaml '             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"'
        Add-Content App.xaml '             StartupUri="MainWindow.xaml">'
        Add-Content App.xaml '    <Application.Resources>'
        Add-Content App.xaml '    </Application.Resources>'
        Add-Content App.xaml '</Application>'
        
        # Create App.xaml.cs
        New-Item -Path App.xaml.cs -Force
        Add-Content App.xaml.cs 'using System.Windows;'
        Add-Content App.xaml.cs ''
        Add-Content App.xaml.cs 'namespace KOALAOptimizer'
        Add-Content App.xaml.cs '{'
        Add-Content App.xaml.cs '    public partial class App : Application'
        Add-Content App.xaml.cs '    {'
        Add-Content App.xaml.cs '    }'
        Add-Content App.xaml.cs '}'
        
        # Create project file
        New-Item -Path KOALAOptimizer.Testing.csproj -Force
        Add-Content KOALAOptimizer.Testing.csproj '<Project Sdk="Microsoft.NET.Sdk">'
        Add-Content KOALAOptimizer.Testing.csproj '  <PropertyGroup>'
        Add-Content KOALAOptimizer.Testing.csproj '    <OutputType>WinExe</OutputType>'
        Add-Content KOALAOptimizer.Testing.csproj '    <TargetFramework>net8.0-windows</TargetFramework>'
        Add-Content KOALAOptimizer.Testing.csproj '    <RuntimeIdentifier>win-x64</RuntimeIdentifier>'
        Add-Content KOALAOptimizer.Testing.csproj '    <UseWPF>true</UseWPF>'
        Add-Content KOALAOptimizer.Testing.csproj '    <AssemblyName>KOALAOptimizer</AssemblyName>'
        Add-Content KOALAOptimizer.Testing.csproj '    <RootNamespace>KOALAOptimizer</RootNamespace>'
        Add-Content KOALAOptimizer.Testing.csproj '    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>'
        Add-Content KOALAOptimizer.Testing.csproj '    <PublishSingleFile>true</PublishSingleFile>'
        Add-Content KOALAOptimizer.Testing.csproj '    <SelfContained>true</SelfContained>'
        Add-Content KOALAOptimizer.Testing.csproj '  </PropertyGroup>'
        Add-Content KOALAOptimizer.Testing.csproj '  <ItemGroup>'
        Add-Content KOALAOptimizer.Testing.csproj '    <PackageReference Include="System.Management" Version="8.0.0" />'
        Add-Content KOALAOptimizer.Testing.csproj '    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />'
        Add-Content KOALAOptimizer.Testing.csproj '  </ItemGroup>'
        Add-Content KOALAOptimizer.Testing.csproj '</Project>'
        
        # Create AssemblyInfo
        New-Item -Path Properties\AssemblyInfo.cs -Force
        Add-Content Properties\AssemblyInfo.cs 'using System.Reflection;'
        Add-Content Properties\AssemblyInfo.cs '[assembly: AssemblyTitle("KOALA Gaming Optimizer V3")]'
        Add-Content Properties\AssemblyInfo.cs '[assembly: AssemblyCompany("KOALAaufPILLEN")]'
        Add-Content Properties\AssemblyInfo.cs '[assembly: AssemblyVersion("3.0.0.0")]'
        
        Write-Host "=== FILES CREATED WITH ADD-CONTENT ==="
        Get-ChildItem
      shell: pwsh
    
    - name: Build and Publish
      run: |
        cd KOALAOptimizer.Testing
        
        Write-Host "=== RESTORE ==="
        dotnet restore
        
        Write-Host "=== BUILD ==="
        dotnet build -c Release
        
        Write-Host "=== PUBLISH ==="
        dotnet publish -c Release -o ../output
        
        cd ..
        
        Write-Host "=== BUILD COMPLETE! ==="
        Get-ChildItem output
      shell: pwsh
    
    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: KOALA-V3-WORKING
        path: output/
